### ISSUE TITLE
Support for exec and npx

### ISSUE THREAD

**Issue by bradzacher** [armano2/npm-to-yarn#4]
If you want to list a "run" command, currently this is not supported.

```
$ npm exec eslint
$ npx eslint
# ->
$ yarn eslint
# or
$ yarn run eslint
```

**Comment by armano2** [comment]
`npx` can't be converted to yarn, as there is no similar functionality

for example:
```
npx -p @storybook/cli sb init
```
in teory you could do something like

```
yarn global add @storybook/cli
yarn exec sb init
```

but this is still not fully accurate, as for exec i'm going to push a patch

**Comment by armano2** [comment]
update: npm exec is now correctly supported, and all changes has been merged to https://github.com/nebrelbug/npm-to-yarn

https://nebrelbug.github.io/npm-to-yarn/test.html
