### ISSUE TITLE
Not sure if `npm run` is transformed correctly

### ISSUE THREAD

**Issue by mrazauskas** [armano2/npm-to-yarn#6]
**Describe the bug**

Thanks for creating a fork!

I was playing with `npm run` command. To be honest, I do not use NPM regularly, might be this is expected:

`npm run test -- --version` -> `yarn run test --version` (ok)
`npm run test -- -v` -> `yarn run test -- -v` (?)

`npm test -- --version` -> `yarn test -- --version` (?)
`npm test -- -v` -> `yarn test -- -v` (?)

Feels like `--` should be skipped in all `yarn` commands. Or did I miss something?

**Package & Environment Details**

"@armano/npm-to-yarn": "^1.1.3"

**Comment by armano2** [comment]
fixed in npm-to-yarn
