### ISSUE TITLE
`--save-exact` for `npm install` isn't converted correctly

### ISSUE THREAD

**Issue by favna** [armano2/npm-to-yarn#7]
**Describe the bug**
I found this fork through your contribution to Docusaurus. Seeing as the source repository appears to be dead I'm creating the issue here hoping you can fix this.

There is currently a bug with `npm install pkg --save-exact` getting converted to `yarn add pkg-exact` instead of `yarn add pkg --exact`

**To Reproduce**

1. Pass `npm install pkg --save-exact` to the npm-to-yarn with second argument set to `yarn`
2. Observe result 

**Expected behavior**
Gets converted to `yarn add pkg --exact`

**Package & Environment Details**

- Environment: Node v18.4.0
- Version: 1.1.1

**Additional context**
N.A.

**Comment by armano2** [comment]
fixed in `npm-to-yarn`
